"use client";
import { useState } from "react";
import Link from "next/link";
import { ArrowLeft, Check, CreditCard, KeyRound, LockKeyhole } from "lucide-react";

export default function AccountPanel({user,signOutPath}:{user:{name:string,email:string},signOutPath:string}) {
  const [key, setKey] = useState(""); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false);
  async function saveKey(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage("");try{const res=await fetch("/api/keys",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({provider:"music-ai",apiKey:key})});const data=await res.json();setMessage(res.ok?"Clave cifrada y guardada.":data.error||"No se pudo guardar.");if(res.ok)setKey("")}catch{setMessage("No se pudo conectar. Inténtalo de nuevo.")}finally{setBusy(false)}}
  async function checkout(){setBusy(true);try{const res=await fetch("/api/billing/checkout",{method:"POST"});const data=await res.json();if(res.ok&&data.url) location.href=data.url;else setMessage(data.error||"La facturación aún no está configurada.")}catch{setMessage("No se pudo conectar. Inténtalo de nuevo.")}finally{setBusy(false)}}
  return <main className="account-page"><div className="account-wrap"><Link className="back-link" href="/"><ArrowLeft size={16}/> Editor</Link><header className="account-header"><div><span className="account-mark">AK</span><h1>Cuenta</h1><p>{user.name} · {user.email}</p></div><a href={signOutPath} target="_top">Cerrar sesión</a></header><div className="account-grid"><section className="account-card"><div className="account-card-title"><CreditCard/><h2>Plan</h2><span>Gratis</span></div><ul><li><Check/> 1 karaoke por semana</li><li><Check/> Exportación con marca de agua</li><li><Check/> Separación estándar</li></ul><button className="checkout" onClick={checkout} disabled={busy}>Mejorar · $13/mes</button></section><section className="account-card"><div className="account-card-title"><KeyRound/><h2>Separación premium</h2><span>Próximamente</span></div><p>Conecta Moises.ai o Music.ai. La clave se cifra y nunca vuelve al navegador.</p><form onSubmit={saveKey}><label>API key<input type="password" required minLength={20} placeholder="••••••••••••••••" value={key} onChange={e=>setKey(e.target.value)}/></label><button disabled={busy||!key}><LockKeyhole size={16}/> Guardar clave</button></form></section></div>{message&&<div className="account-message" role="status">{message}</div>}</div></main>
}
