"use client";
import {useEffect,useState} from "react";
import Image from "next/image";
import {ArrowLeft,Check,CreditCard,FolderPlus,Plus,Trash2,Type} from "lucide-react";
import {authClient} from "../../lib/auth-client";
import type {PlanSnapshot} from "../../lib/plans";

type Collection={id:string;name:string;fonts:string[]};
type CollectionsResponse={collections?:Collection[]};
type CreateCollectionResponse={collection?:Collection;error?:string};
export type AccountSection="profile"|"plans"|"fonts";

export default function AccountPanel({user,plan,section}:{user:{name:string,email:string};plan:PlanSnapshot;section:AccountSection}){
 const[collections,setCollections]=useState<Collection[]>([]);const[name,setName]=useState("");const[message,setMessage]=useState("");const[busy,setBusy]=useState(false);
 useEffect(()=>{if(section!=="fonts")return;let cancelled=false;void fetch("/api/font-collections").then(async r=>r.ok?await r.json() as CollectionsResponse:{collections:[]}).then(d=>{if(!cancelled)setCollections(d.collections||[])}).catch(()=>{if(!cancelled)setMessage("Could not load font collections.")});return()=>{cancelled=true}},[section]);
 async function createCollection(e:React.FormEvent){e.preventDefault();if(!name.trim())return;setBusy(true);setMessage("");try{const r=await fetch("/api/font-collections",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name})});const d=await r.json() as CreateCollectionResponse;if(r.ok&&d.collection){setCollections(c=>[...c,d.collection!]);setName("");setMessage("Collection created.")}else setMessage(d.error||"The collection could not be created.")}catch{setMessage("The collection could not be created.")}finally{setBusy(false)}}
 async function remove(id:string){try{const r=await fetch(`/api/font-collections?id=${encodeURIComponent(id)}`,{method:"DELETE"});if(r.ok)setCollections(c=>c.filter(v=>v.id!==id));else setMessage("The collection could not be deleted.")}catch{setMessage("The collection could not be deleted.")}}
 async function checkout(){setBusy(true);setMessage("");try{const r=await fetch("/api/billing/checkout",{method:"POST"});const d=await r.json() as{url?:string;error?:string};if(r.ok&&d.url){window.location.href=d.url;return}setMessage(d.error||"Checkout could not be started.")}catch{setMessage("Checkout could not be started.")}finally{setBusy(false)}}
 const title=section==="plans"?"Plans":section==="fonts"?"Font collections":"Profile";
 return <main className="account-page"><div className="account-wrap"><a className="back-link" href="/studio"><ArrowLeft size={16}/> Studio</a><header className="account-header"><div><span className="account-mark"><Image src="/logoak.svg" alt="" width={1080} height={1080}/></span><h1>{title}</h1><p>{user.name} · {user.email}</p></div><button type="button" onClick={()=>void authClient.signOut({fetchOptions:{onSuccess:()=>{window.location.href="/"}}})}>Sign out</button></header>
  <nav className="account-section-nav" aria-label="Account settings"><a href="/account" aria-current={section==="profile"?"page":undefined} className={section==="profile"?"active":""}>Profile</a><a href="/account/plans" aria-current={section==="plans"?"page":undefined} className={section==="plans"?"active":""}>Plans</a><a href="/account/fonts" aria-current={section==="fonts"?"page":undefined} className={section==="fonts"?"active":""}>Font collections</a></nav>
  {section==="profile"&&<section className="account-card profile-details"><h2>Basic profile</h2><dl><div><dt>Name</dt><dd>{user.name}</dd></div><div><dt>Email</dt><dd>{user.email}</dd></div></dl></section>}
  {section==="plans"&&<div className="plan-grid"><section className={`account-card plan-card ${plan.plan==="free"?"current-plan":""}`}><div className="account-card-title"><CreditCard/><h2>Free</h2>{plan.plan==="free"&&<span>Current plan</span>}</div><div className="plan-price">$0 <small>/ month</small></div><ul><li><Check/> 1 karaoke video per week</li><li><Check/> Open-source BS-RoFormer separation</li><li><Check/> Watermarked export</li></ul><div className="plan-usage">{plan.usedThisWeek} of 1 used this week</div></section><section className={`account-card plan-card ${plan.plan==="pro"?"current-plan":""}`}><div className="account-card-title"><CreditCard/><h2>Pro</h2>{plan.plan==="pro"&&<span>Current plan</span>}</div><div className="plan-price">$13 <small>/ month</small></div><ul><li><Check/> Unlimited karaoke videos</li><li><Check/> Highest-quality separation</li><li><Check/> No watermark</li></ul>{plan.plan==="pro"?<button className="checkout" disabled>Active</button>:<button className="checkout" disabled={busy} onClick={()=>void checkout()}>{busy?"Opening checkout…":"Upgrade to Pro"}</button>}</section></div>}
  {section==="fonts"&&<section className="account-card fonts-card"><div className="account-card-title"><Type/><h2>Font collections</h2><span>Saved to your account</span></div><p>Projects, audio, and videos are never stored. Only your font collections persist.</p><form onSubmit={createCollection}><label>Collection name<input value={name} onChange={e=>setName(e.target.value)} placeholder="Favorite karaoke fonts" maxLength={40}/></label><button disabled={busy||!name.trim()}><FolderPlus size={16}/> Create collection</button></form>{collections.map(c=><div className="font-collection" key={c.id}><span><b>{c.name}</b><small>{c.fonts.length} fonts</small></span><button type="button" aria-label={`Delete ${c.name}`} onClick={()=>void remove(c.id)}><Trash2/></button></div>)}{!collections.length&&<div className="empty-collection"><Plus/> No collections yet</div>}</section>}
  {message&&<div className="account-message" role="status">{message}</div>}</div></main>
}
